# -- EXTENSION USED FOR TESTING REST API REQUESTS --
# --------------------------------------------------
# Id: humao.rest-client
# Description: REST Client for Visual Studio Code
# Version: 0.25.1
# Publisher: Huachao Mao
# VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# --------------------------------------------------

### GET Products
GET http://localhost:5000/products

### GET Product by ID
GET http://localhost:5000/products/1

### POST Create Product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 100,
    "description": "This is product 1"
}

### PUT Update Product

PUT http://localhost:5000/products/5
Content-Type: application/json

{
    "name": "Product 1 Updated",
    "price": 200,
    "description": "This is product 1 updated"
}

### DELETE Product
DELETE http://localhost:5000/products/6